#! /bin/sh

bspc monitor DVI-I-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config focused_border_color "#b948be"

bspc config border_width         3
bspc config window_gap           8

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Firefox desktop=www
bspc rule -a Firefox:Dialog state=floating
bspc rule -a Firefox:SessionManager state=floating layer=above
