#! /bin/sh

/home/kieran/.xinitrc

bspc monitor DP-0 -d www term λ
bspc monitor DVI-I-0 -d www term λ
bspc config focused_border_color "#b948be"


bspc config border_width         2
bspc config window_gap           0
#bspc config -m DP-0 top_padding 20
#bspc config -m DP-0 bottom_padding 20
#bspc config -m DVI-I-0 bottom_padding 20


bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a '*' desktop=focused:λ focus=on follow=on
bspc rule -a Firefox desktop=focused:www
bspc rule -a Termite desktop=focused:term
bspc rule -a Firefox:Dialog state=floating
bspc rule -a Firefox:SessionManager state=floating layer=above
